osx_image: xcode7.3
language: objective-c

script:
- open -b com.apple.iphonesimulator
- set -o pipefail && xcodebuild test
    -project RemoteLogger.xcodeproj
    -scheme RemoteLogger
    -sdk iphonesimulator9.3
    -destination "iOS Simulator,name=iPhone 6s"
    ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
