osx_image: xcode7.3
language: objective-c

before_install:
  - xcrun simctl list

script:
- open -b com.apple.iphonesimulator
- set -o pipefail && env NSUnbufferedIO=YES xcodebuild test
    -project RemoteLogger.xcodeproj
    -scheme RemoteLogger
    -sdk iphonesimulator
    -destination "platform=iOS Simulator,name=iPhone 6s,OS=9.3"
    ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
