osx_image: xcode7.3
language: objective-c

before_install:
  - xcrun simctl list
  - brew update || brew update

script:
  - open -b com.apple.iphonesimulator
  - set -o pipefail && env NSUnbufferedIO=YES xcodebuild test -project RemoteLogger.xcodeproj -scheme RemoteLogger -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6s,OS=9.3"
  - pod lib lint
